"""Simulate the target slicer's config loader and assert it would accept our
output.

Every "it doesn't work" report in this project's history traced back to the
same place: `ConfigBase::load_from_json` in the target slicer. Its failure
modes are narrow and knowable, and this module reproduces them so a broken
conversion fails here instead of in front of the user.

From BambuStudio's own source (`src/libslic3r/Config.cpp`,
`src/libslic3r/Format/bbs_3mf.cpp`), loading a project's config:

  * A **string**-valued key goes to `set_deserialize`, which applies
    `handle_legacy` and then throws if the option is unknown
    (`UnknownOptionException`) or the value doesn't parse for its declared
    type (`BadOptionValueException`).
  * An **array**-valued key is looked up first and silently recorded as
    unrecognised if unknown -- so arrays are survivable, strings are not.
  * A value that fails to parse is only *survivable* for `coEnum`, `coEnums`
    and `coBool(s)`: `set_deserialize_raw` falls back to the option's default
    and records a substitution. That is the "configuration may have been
    generated by a newer version -- some values have been replaced" dialog,
    and it is recoverable. For every other type a parse failure throws.
  * Any throw is caught as a generic exception, `load_from_json` returns -1,
    and `_extract_project_config_from_archive` reports it. The user sees
    "Invalid configuration file" *and* "The file does not contain any
    geometry data", because the load aborted before the model was read.

Real project files written by the real slicers are used as controls: if this
simulation flagged them, the simulation itself would be wrong. It did, at
first -- they carry enum values their own slicer substitutes -- which is how
the fatal/recoverable split above got pinned down instead of assumed.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from convert.pipeline import MODEL_REGISTRY, convert
from core.archive import ThreeMFArchive
from core.vocabulary import load_enums, load_option_types, load_vocabulary, value_fits_type

from .conftest import DOWNLOADS, sample_path

PROFILES = Path(__file__).parent.parent / "profiles"
BAMBU = PROFILES / "bambu_h2c"
SNAPMAKER = PROFILES / "snapmaker_u1"

_REAL_SLICER_FILES = {
    "h2c_antiwarp": (DOWNLOADS / "תלת מימד" / "H2C_Anti-Warp-UltimateDiffuser-H2.3mf", BAMBU),
    "voronoi_nonu1": (DOWNLOADS / "Voronoi+Toucan+AMS+170%" / "Voronoi+Toucan+AMS+170%.3mf", BAMBU),
    "h2d_hedgehog": (DOWNLOADS / "תלת מימד" / "ArticulatedCuteHedgehog_Multicolor4ColorBambuStudioH2D.3mf", BAMBU),
    "a1mini_benchy": (DOWNLOADS / "תלת מימד" / "benchy ams test.3mf", BAMBU),
}


_SUBSTITUTABLE_TYPES = {"coEnum", "coEnums", "coBool", "coBools"}


def find_load_errors(config: dict, vendor_dir: Path) -> list[str]:
    """Everything that would make the target slicer *reject* this config."""
    vocabulary = load_vocabulary(vendor_dir)
    option_types = load_option_types(vendor_dir)
    errors: list[str] = []

    for key, value in config.items():
        # Unknown *string* keys throw; unknown array keys are tolerated.
        if key not in vocabulary and isinstance(value, str):
            errors.append(f"UnknownOptionException: {key}")

        option_type = option_types.get(key)
        if not option_type or option_type in _SUBSTITUTABLE_TYPES:
            continue
        for item in value if isinstance(value, list) else [value]:
            if isinstance(item, str) and not value_fits_type(option_type, item):
                errors.append(f"BadOptionValueException: {key}={item!r} is not a valid {option_type}")

    return errors


def find_substitutions(config: dict, vendor_dir: Path) -> list[str]:
    """Values the target would silently replace with its own default, behind
    the "some values have been replaced" dialog. Not fatal, but every one is
    a setting the user chose and won't get."""
    enums = load_enums(vendor_dir)
    notes: list[str] = []
    for key, value in config.items():
        entry = enums.get(key)
        if not entry:
            continue
        for item in value if isinstance(value, list) else [value]:
            if isinstance(item, str) and item and item not in entry["values"]:
                notes.append(f"{key}={item!r} -> default")
    return notes


def _config(path_or_archive) -> dict:
    archive = path_or_archive if isinstance(path_or_archive, ThreeMFArchive) else ThreeMFArchive.open(path_or_archive)
    return json.loads(archive.get_text("Metadata/project_settings.config"))


@pytest.mark.parametrize("name", sorted(_REAL_SLICER_FILES))
def test_simulation_accepts_files_the_real_slicers_wrote(name):
    """Control. These files demonstrably load, so a simulation that rejects
    one is broken and its verdict on our output would be worthless."""
    path, vendor_dir = _REAL_SLICER_FILES[name]
    if not path.exists():
        pytest.skip(f"sample not present: {path}")

    assert find_load_errors(_config(path), vendor_dir) == []


def test_simulation_accepts_real_u1_files_against_the_snapmaker_definition():
    for name in ("u1_majorasmask", "u1_toucan_plus", "voronoi_u1"):
        assert find_load_errors(_config(sample_path(name)), SNAPMAKER) == [], name


def test_simulation_catches_the_bug_that_broke_the_real_conversion():
    """The actual defect: Snapmaker declares `skeleton_infill_line_width` as
    coFloatOrPercent and stores "100%"; Bambu declares it a plain coFloat and
    throws. Feeding a U1 config to the Bambu definition unchanged must be
    reported."""
    errors = find_load_errors(_config(sample_path("u1_toucan_plus")), BAMBU)

    assert any("skeleton_infill_line_width" in e for e in errors), errors
    assert all(e.startswith(("UnknownOptionException", "BadOptionValueException")) for e in errors)


@pytest.mark.parametrize(
    "source_name,target",
    [
        ("u1_toucan_plus", "h2c"),
        ("u1_majorasmask", "h2c"),
        ("u1_majorasmask", "h2d"),
        ("voronoi_u1", "h2c"),
        ("h2c_antiwarp", "u1"),
        ("h2c_antiwarp", "a1-mini"),
        ("benchy_ams", "u1"),
    ],
)
def test_converted_files_would_load(source_name, target):
    archive, _ = convert(sample_path(source_name), target)
    vendor_dir = SNAPMAKER if target == "u1" else BAMBU

    assert find_load_errors(_config(archive), vendor_dir) == [], (source_name, target)


@pytest.mark.parametrize("target", sorted(set(MODEL_REGISTRY) - {"u1"}))
def test_every_bambu_target_would_load(target):
    archive, _ = convert(sample_path("u1_toucan_plus"), target)
    assert find_load_errors(_config(archive), BAMBU) == [], target


@pytest.mark.parametrize(
    "source_name,target",
    [("u1_toucan_plus", "h2c"), ("u1_majorasmask", "h2d"), ("h2c_antiwarp", "u1"), ("h2c_antiwarp", "a1-mini")],
)
def test_converted_files_do_not_even_trigger_the_substitution_dialog(source_name, target):
    """Substitutions are survivable, but each one silently discards a setting
    the user picked -- and they're what produced the "generated by a newer
    version" dialog. convert/pipeline.py resolves them up front instead."""
    archive, _ = convert(sample_path(source_name), target)
    vendor_dir = SNAPMAKER if target == "u1" else BAMBU

    assert find_substitutions(_config(archive), vendor_dir) == [], (source_name, target)
